image: gitpod/workspace-full
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Working terminal
    command: echo "Working terminal"
  - name: Init backend api
    init: docker load -i webapi.tar # runs during prebuild
    command: docker run -it -p 3000:3000 webapi
    openMode: split-right
  - name: Get backend dynamic url
    command: gp url 3000 > WebApp/url.txt
#   - name: Init front end
#     init: cd WebApp
#     command: python -m http.server 3001
#     openMode: split-right
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: open-preview

vscode:
  extensions:
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - johnsoncodehk.volar
