image: gitpod/workspace-full
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Working terminal
    command: echo "Working terminal"
  - name: Init backend api
    init: docker load -i webapi.tar # runs during prebuild
    command: docker run -it -p 3000:3000 webapi
    openMode: split-right

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
