image: gitpod/workspace-full
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Working terminal
    command: echo "Working terminal"

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
